# -*- coding: utf-8 -*-
"""Lab 2 - Data Encryption Standard (DES)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19mCcFB6sOybhcfyCZB0tH39DDtMvhKDj
"""

#install-PyCryptodome
#to do
!pip install pycryptodome

from Crypto.Cipher import DES
from Crypto.Random import get_random_bytes

def pad_text(text):
    # Ensure the plaintext length is a multiple of 8 bytes (DES block size)
    #generate and return the padded_text
    block_size = 8
    #to do

    num_padding_bytes = block_size - (len(text) % block_size)
    if num_padding_bytes == 0:
        num_padding_bytes = block_size

    # Create the padding: num_padding_bytes, repeated num_padding_bytes times.
    padded_text = text + bytes([num_padding_bytes] * num_padding_bytes)

    return padded_text

def unpad_text(padded_text):
    # Remove the padding bytes to get the original plaintext
    #to do
    return padded_text.rstrip(b'\x00')

def des_encrypt(plaintext, key):
    #encrypt DES(Mode:ECB) and return the ciphertext
    cipher = DES.new(key, DES.MODE_ECB)
    ciphertext = cipher.encrypt(plaintext)
    return ciphertext

plaintext = b"This is a secret text"
# Generate a random 64-bit (8-byte) key
#to do
key = get_random_bytes(8)

print("Original plaintext:", plaintext.decode('utf-8'))
print("Original key (in bytes):", key)

plaintext = pad_text(plaintext)

ciphertext = des_encrypt(plaintext, key)
print("Encrypted ciphertext (in bytes):", ciphertext)

def des_decrypt(ciphertext, key):
  #decrypt DES(Mode:ECB) and return the plaintext
  cipher = DES.new(key, DES.MODE_ECB)
  plaintext = cipher.decrypt(ciphertext)
  return plaintext

ciphertext = b"\x1c\xd3Y\x13\xcfe\xb7\xdf\x13\x9dA\xaapY\xd7\xf0+\xd9L\x87\xa5\x1eTc"
key = b"\xe4\xc0yX\x97\xa8\x13\x12"

decrypted_text = des_decrypt(ciphertext, key)
original_text = unpad_text(decrypted_text)

print("Decrypted text:", original_text.decode('utf-8'))

#Implement Double DES and check if your ciphertext matches the provided output.
plaintext = b"I am Batman"
KeyA = b'\x01\xadWR\xeb\x1a\xa2\x86'
KeyB = b'\xf7\xcf\xd6r\xd9\xa1\x141'
Given_Output = b'\xd2Em\x06-1\xf7$\x0c\xaaI\xf0\xc3\x00\xbd}'

#to do
padtext = pad_text(plaintext)
c1 = des_encrypt(padtext,KeyA)
c2 = des_encrypt(c1,KeyB)
print(c2)

#Pattern Repetition in DES ECB Mode Ciphertext
plaintext = b"ABCDEFGHABCDEFGHABCDEFGH"
key = get_random_bytes(8)  # Generate a random 64-bit (8-byte) key

padtext = pad_text(plaintext)
c1 = des_encrypt(padtext,key)
print(c1)

# DES reveal pattrn
# block cypher revels patterns